"""
Consist: Automatic provenance tracking and intelligent caching for scientific simulation workflows.

This package provides the main public API for Consist, allowing users to interact with
the Tracker for managing runs, logging artifacts, and ingesting data.
"""

# Models
from consist.models.run import Run, RunResult
from consist.models.artifact import Artifact
from consist.runset import AlignedPair, RunSet

# Core
from consist.core.tracker import Tracker
from consist.core.coupler import Coupler
from consist.core.indexing import (
    FacetIndex,
    RunFieldIndex,
    index_by_facet,
    index_by_field,
)

# API
from consist.api import (
    load,
    load_df,
    load_relation,
    active_relation_count,
    RelationConnectionLeakWarning,
    to_df,
    run,
    ref,
    refs,
    trace,
    start_run,
    log_artifact,
    log_input,
    log_output,
    log_artifacts,
    log_dataframe,
    define_step,
    require_runtime_kwargs,
    ingest,
    capture_outputs,
    use_tracker,
    set_current_tracker,
    current_tracker,
    current_run,
    current_consist,
    output_dir,
    output_path,
    log_meta,
    view,
    cached_output,
    cached_artifacts,
    get_run_result,
    hydrate_run_outputs,
    materialize_run_outputs,
    stage_artifact,
    stage_inputs,
    set_artifact_recovery_roots,
    archive_artifact,
    archive_run_outputs,
    archive_current_run_outputs,
    get_artifact,
    register_artifact_facet_parser,
    scenario,
    noop_scenario,
    single_step_scenario,
    register_views,
    find_run,
    find_runs,
    find_latest_run,
    run_set,
    db_session,
    run_query,
    config_run_query,
    config_run_rows,
    pivot_facets,
    # Type guards for artifact narrowing
    is_dataframe_artifact,
    is_tabular_artifact,
    is_json_artifact,
    is_zarr_artifact,
    is_hdf_artifact,
    is_spatial_artifact,
)

# Types
from consist.types import (
    BindingResult,
    CacheOptions,
    DriverType,
    ExecutionOptions,
    H5ChildSpec,
    OutputPolicyOptions,
)
from consist.core.noop import (
    NoopArtifact,
    NoopCoupler,
    NoopRunResult,
    NoopScenarioContext,
    NoopTracker,
)
from consist.core.materialize import (
    HydratedRunOutput,
    HydratedRunOutputsResult,
    MaterializationResult,
    StagedInput,
    StagedInputsResult,
)
from consist.runtime import create_tracker
from consist.protocols import (
    ArtifactLike,
    RunIdentifiedResultLike,
    RunResultLike,
    ScenarioLike,
    TrackerLike,
)

__all__ = [
    # Core objects
    "Tracker",
    "Coupler",
    "Run",
    "RunResult",
    "Artifact",
    "RunSet",
    "AlignedPair",
    # Types
    "BindingResult",
    "DriverType",
    "CacheOptions",
    "OutputPolicyOptions",
    "ExecutionOptions",
    "H5ChildSpec",
    "NoopArtifact",
    "NoopCoupler",
    "NoopRunResult",
    "NoopScenarioContext",
    "NoopTracker",
    "HydratedRunOutput",
    "HydratedRunOutputsResult",
    "MaterializationResult",
    "StagedInput",
    "StagedInputsResult",
    "create_tracker",
    "ArtifactLike",
    "RunIdentifiedResultLike",
    "RunResultLike",
    "ScenarioLike",
    "TrackerLike",
    # Indexing helpers
    "FacetIndex",
    "RunFieldIndex",
    "index_by_facet",
    "index_by_field",
    # Functional helpers
    "load",
    "load_df",
    "load_relation",
    "active_relation_count",
    "RelationConnectionLeakWarning",
    "to_df",
    "run",
    "ref",
    "refs",
    "trace",
    "start_run",
    "log_artifact",
    "log_input",
    "log_output",
    "log_artifacts",
    "log_dataframe",
    "define_step",
    "require_runtime_kwargs",
    "ingest",
    "capture_outputs",
    "use_tracker",
    "set_current_tracker",
    "current_tracker",
    "current_run",
    "current_consist",
    "output_dir",
    "output_path",
    "log_meta",
    "view",
    "cached_output",
    "cached_artifacts",
    "get_run_result",
    "hydrate_run_outputs",
    "materialize_run_outputs",
    "stage_artifact",
    "stage_inputs",
    "set_artifact_recovery_roots",
    "archive_artifact",
    "archive_run_outputs",
    "archive_current_run_outputs",
    "get_artifact",
    "register_artifact_facet_parser",
    "scenario",
    "noop_scenario",
    "single_step_scenario",
    "register_views",
    "find_run",
    "find_runs",
    "find_latest_run",
    "run_set",
    "db_session",
    "run_query",
    "config_run_query",
    "config_run_rows",
    "pivot_facets",
    # Type guards for artifact narrowing
    "is_dataframe_artifact",
    "is_tabular_artifact",
    "is_json_artifact",
    "is_zarr_artifact",
    "is_hdf_artifact",
    "is_spatial_artifact",
]
